### PR TITLE
Disabled wan_check service

### PR DESCRIPTION
**Pull request by BanForFun**
When I set the router to access point mode, my pihole was logging dns requests to api.miwifi.com every 8 seconds. I found the cause to be the `wan_check` service being manually started by `/usr/sbin/ap_mode.sh`. I fixed it by adding a return statement in the beginning of the start_service method.

### CODE REVIEW

**Comment by progms4** [comment]
Does it mean that the led that indicate internet connectivity will not be updated?

**Comment by BanForFun** [comment]
Yes, It will always be off, even in access point mode (currently it is only off when in router mode)

**Comment by geekman** [comment]
@BanForFun wan_check was already "disabled" by removing it from `/etc/init.d/`, which should prevent it from starting. Is there a reason you are more permanently disabling it by editing the service file itself? 

Generally, I would like for someone who _really_ wants wan_check functionality to be able to re-enable it.

**Comment by BanForFun** [comment]
@geekman Your script does remove wan_check from init.d but from rc.d, and the script at /usr/sbin/ap_mode.sh (which is only executed on access point mode) calls `/etc/init.d/wan_check restart` which still exists. That is why I disabled it the way that I did.

**Pull request merged**
